services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false
        Sylius\Component\Resource\Model\ResourceInterface:
            autowire: false

    Lwc\SettingsBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Lwc\SettingsBundle\Form\:
        resource: '../../Form'
        tags: ['form.type']

    Lwc\SettingsBundle\Processor\:
        resource: '../../Processor'

    Lwc\SettingsBundle\Factory\Form\:
        resource: '../../Factory/Form'

    Lwc\SettingsBundle\Twig\Extension\:
        resource: '../../Twig/Extension'
        tags: ['twig.extension']

    Lwc\SettingsBundle\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    Lwc\SettingsBundle\Menu\SettingsFormMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: lwc.settings.admin.update.form }

    lwc.settings.metadata_registry:
        class: Lwc\SettingsBundle\Settings\Metadata\Registry

    Lwc\SettingsBundle\Settings\Metadata\RegistryInterface: '@lwc.settings.metadata_registry'

    lwc.settings.registry:
        class: Lwc\SettingsBundle\Settings\Registry

    Lwc\SettingsBundle\Settings\RegistryInterface: '@lwc.settings.registry'

